import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/home/hero/Hero'
import { getSession, signIn, signOut, useSession } from 'next-auth/react'
import Link from 'next/link'
import { authOptions } from './api/auth/[...nextauth]'
import { GetServerSideProps } from 'next'
import { getServerSession } from 'next-auth'
import Collections from '@/components/home/Collections'
import Bestseller from '@/components/home/bestseller/Bestseller'
import Newsletter from '@/components/home/newsletter/Newsletter'
import Season from '@/components/home/Season'
import { getAllCollections, getAllProducts } from '@/lib/shopify/api'
import InstGallery from '@/components/home/gallery/InstGallery'

export default function Home({ products, сollections }: any) {
  const { data: session } = useSession()
  console.log('products', products)
  console.log('сollections', сollections)

  const signInButtonNode = () => {
    if (session) {
      return false
    }

    return (
      <div>
        <button onClick={() => signIn('google')}>Sign in</button>
      </div>
    )
  }

  const signOutButtonNode = () => {
    if (!session) {
      return false
    }

    return (
      <div>
        <button onClick={() => signOut()}>Sign out</button>
      </div>
    )
  }

  // if (!session) {
  //   return (
  //     <div className='hero'>
  //       <div className='navbar'>
  //         {signOutButtonNode()}
  //         {signInButtonNode()}
  //       </div>
  //       <div className='text'>You aren't authorized to view this page</div>
  //     </div>
  //   )
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Hero /> */}
      <div className='my-10'>
        {/* <Collections data={сollections} />
        <Season />
        */}
        <Bestseller data={products} />
        <Newsletter />
        <InstGallery />
      </div>

      {/* <StoryblokComponent blok={story.content} /> */}
    </>
  )
}

// export async function getServerSideProps(context: any) {
//   const session = await getServerSession(context.req, context.res, authOptions)

//   if (!session) {
//     return {
//       redirect: {
//         destination: '/',
//         permanent: false,
//       },
//     }
//   }

//   return {
//     props: {
//       session,
//     },
//   }
// }

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  let session = await getServerSession(req, res, authOptions)

  const products = await getAllProducts()
  const сollections = await getAllCollections()

  // if (!session) {
  //   return {
  //     redirect: {
  //       destination: '/',
  //       permanent: false,
  //     },
  //   }
  // }

  return {
    props: {
      session: null,
      products,
      сollections,
    },
  }
  // const session = await getSession({ req })
  // return {
  //   props: {
  //     session,
  //   },
  // }
}
